version: "3.4"
services:
  nyan:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: daviey/nyan-cat-web
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /Users/peckn/Documents/Code/ecs-local/task-definition.json
    networks:
      ecs-local-network: null
    ports:
    - target: 80
      published: 8080
      protocol: tcp
networks:
  ecs-local-network:
    external: true
